// Todos los países y territorios con aduana (ISO 3166-1 alfa-2), con su
// nombre en español y en inglés. Generado con Intl.DisplayNames (datos
// CLDR, con unos pocos nombres ajustados al uso común); los territorios
// deshabitados no están. Ordenado por el nombre en español.

export interface Pais {
  iso: string;
  es: string;
  en: string;
}

export const PAISES: Pais[] = [
  { iso: 'AF', es: 'Afganistán', en: 'Afghanistan' },
  { iso: 'AL', es: 'Albania', en: 'Albania' },
  { iso: 'DE', es: 'Alemania', en: 'Germany' },
  { iso: 'AD', es: 'Andorra', en: 'Andorra' },
  { iso: 'AO', es: 'Angola', en: 'Angola' },
  { iso: 'AI', es: 'Anguila', en: 'Anguilla' },
  { iso: 'AG', es: 'Antigua y Barbuda', en: 'Antigua & Barbuda' },
  { iso: 'SA', es: 'Arabia Saudí', en: 'Saudi Arabia' },
  { iso: 'DZ', es: 'Argelia', en: 'Algeria' },
  { iso: 'AR', es: 'Argentina', en: 'Argentina' },
  { iso: 'AM', es: 'Armenia', en: 'Armenia' },
  { iso: 'AW', es: 'Aruba', en: 'Aruba' },
  { iso: 'AU', es: 'Australia', en: 'Australia' },
  { iso: 'AT', es: 'Austria', en: 'Austria' },
  { iso: 'AZ', es: 'Azerbaiyán', en: 'Azerbaijan' },
  { iso: 'BS', es: 'Bahamas', en: 'Bahamas' },
  { iso: 'BD', es: 'Bangladés', en: 'Bangladesh' },
  { iso: 'BB', es: 'Barbados', en: 'Barbados' },
  { iso: 'BH', es: 'Baréin', en: 'Bahrain' },
  { iso: 'BE', es: 'Bélgica', en: 'Belgium' },
  { iso: 'BZ', es: 'Belice', en: 'Belize' },
  { iso: 'BJ', es: 'Benín', en: 'Benin' },
  { iso: 'BM', es: 'Bermudas', en: 'Bermuda' },
  { iso: 'BY', es: 'Bielorrusia', en: 'Belarus' },
  { iso: 'BO', es: 'Bolivia', en: 'Bolivia' },
  { iso: 'BA', es: 'Bosnia y Herzegovina', en: 'Bosnia & Herzegovina' },
  { iso: 'BW', es: 'Botsuana', en: 'Botswana' },
  { iso: 'BR', es: 'Brasil', en: 'Brazil' },
  { iso: 'BN', es: 'Brunéi', en: 'Brunei' },
  { iso: 'BG', es: 'Bulgaria', en: 'Bulgaria' },
  { iso: 'BF', es: 'Burkina Faso', en: 'Burkina Faso' },
  { iso: 'BI', es: 'Burundi', en: 'Burundi' },
  { iso: 'BT', es: 'Bután', en: 'Bhutan' },
  { iso: 'CV', es: 'Cabo Verde', en: 'Cape Verde' },
  { iso: 'KH', es: 'Camboya', en: 'Cambodia' },
  { iso: 'CM', es: 'Camerún', en: 'Cameroon' },
  { iso: 'CA', es: 'Canadá', en: 'Canada' },
  { iso: 'BQ', es: 'Caribe neerlandés', en: 'Caribbean Netherlands' },
  { iso: 'QA', es: 'Catar', en: 'Qatar' },
  { iso: 'TD', es: 'Chad', en: 'Chad' },
  { iso: 'CZ', es: 'Chequia', en: 'Czechia' },
  { iso: 'CL', es: 'Chile', en: 'Chile' },
  { iso: 'CN', es: 'China', en: 'China' },
  { iso: 'CY', es: 'Chipre', en: 'Cyprus' },
  { iso: 'VA', es: 'Ciudad del Vaticano', en: 'Vatican City' },
  { iso: 'CO', es: 'Colombia', en: 'Colombia' },
  { iso: 'KM', es: 'Comoras', en: 'Comoros' },
  { iso: 'CG', es: 'Congo', en: 'Congo (Brazzaville)' },
  { iso: 'KP', es: 'Corea del Norte', en: 'North Korea' },
  { iso: 'KR', es: 'Corea del Sur', en: 'South Korea' },
  { iso: 'CI', es: 'Costa de Marfil', en: 'Côte d’Ivoire' },
  { iso: 'CR', es: 'Costa Rica', en: 'Costa Rica' },
  { iso: 'HR', es: 'Croacia', en: 'Croatia' },
  { iso: 'CU', es: 'Cuba', en: 'Cuba' },
  { iso: 'CW', es: 'Curazao', en: 'Curaçao' },
  { iso: 'DK', es: 'Dinamarca', en: 'Denmark' },
  { iso: 'DM', es: 'Dominica', en: 'Dominica' },
  { iso: 'EC', es: 'Ecuador', en: 'Ecuador' },
  { iso: 'EG', es: 'Egipto', en: 'Egypt' },
  { iso: 'SV', es: 'El Salvador', en: 'El Salvador' },
  { iso: 'AE', es: 'Emiratos Árabes Unidos', en: 'United Arab Emirates' },
  { iso: 'ER', es: 'Eritrea', en: 'Eritrea' },
  { iso: 'SK', es: 'Eslovaquia', en: 'Slovakia' },
  { iso: 'SI', es: 'Eslovenia', en: 'Slovenia' },
  { iso: 'ES', es: 'España', en: 'Spain' },
  { iso: 'US', es: 'Estados Unidos', en: 'United States' },
  { iso: 'EE', es: 'Estonia', en: 'Estonia' },
  { iso: 'SZ', es: 'Esuatini', en: 'Eswatini' },
  { iso: 'ET', es: 'Etiopía', en: 'Ethiopia' },
  { iso: 'PH', es: 'Filipinas', en: 'Philippines' },
  { iso: 'FI', es: 'Finlandia', en: 'Finland' },
  { iso: 'FJ', es: 'Fiyi', en: 'Fiji' },
  { iso: 'FR', es: 'Francia', en: 'France' },
  { iso: 'GA', es: 'Gabón', en: 'Gabon' },
  { iso: 'GM', es: 'Gambia', en: 'Gambia' },
  { iso: 'GE', es: 'Georgia', en: 'Georgia' },
  { iso: 'GH', es: 'Ghana', en: 'Ghana' },
  { iso: 'GI', es: 'Gibraltar', en: 'Gibraltar' },
  { iso: 'GD', es: 'Granada', en: 'Grenada' },
  { iso: 'GR', es: 'Grecia', en: 'Greece' },
  { iso: 'GL', es: 'Groenlandia', en: 'Greenland' },
  { iso: 'GP', es: 'Guadalupe', en: 'Guadeloupe' },
  { iso: 'GU', es: 'Guam', en: 'Guam' },
  { iso: 'GT', es: 'Guatemala', en: 'Guatemala' },
  { iso: 'GF', es: 'Guayana Francesa', en: 'French Guiana' },
  { iso: 'GG', es: 'Guernesey', en: 'Guernsey' },
  { iso: 'GN', es: 'Guinea', en: 'Guinea' },
  { iso: 'GQ', es: 'Guinea Ecuatorial', en: 'Equatorial Guinea' },
  { iso: 'GW', es: 'Guinea-Bisáu', en: 'Guinea-Bissau' },
  { iso: 'GY', es: 'Guyana', en: 'Guyana' },
  { iso: 'HT', es: 'Haití', en: 'Haiti' },
  { iso: 'HN', es: 'Honduras', en: 'Honduras' },
  { iso: 'HK', es: 'Hong Kong', en: 'Hong Kong' },
  { iso: 'HU', es: 'Hungría', en: 'Hungary' },
  { iso: 'IN', es: 'India', en: 'India' },
  { iso: 'ID', es: 'Indonesia', en: 'Indonesia' },
  { iso: 'IQ', es: 'Irak', en: 'Iraq' },
  { iso: 'IR', es: 'Irán', en: 'Iran' },
  { iso: 'IE', es: 'Irlanda', en: 'Ireland' },
  { iso: 'IM', es: 'Isla de Man', en: 'Isle of Man' },
  { iso: 'CX', es: 'Isla de Navidad', en: 'Christmas Island' },
  { iso: 'NF', es: 'Isla Norfolk', en: 'Norfolk Island' },
  { iso: 'IS', es: 'Islandia', en: 'Iceland' },
  { iso: 'AX', es: 'Islas Aland', en: 'Åland Islands' },
  { iso: 'KY', es: 'Islas Caimán', en: 'Cayman Islands' },
  { iso: 'CC', es: 'Islas Cocos', en: 'Cocos (Keeling) Islands' },
  { iso: 'CK', es: 'Islas Cook', en: 'Cook Islands' },
  { iso: 'FO', es: 'Islas Feroe', en: 'Faroe Islands' },
  { iso: 'FK', es: 'Islas Malvinas', en: 'Falkland Islands' },
  { iso: 'MP', es: 'Islas Marianas del Norte', en: 'Northern Mariana Islands' },
  { iso: 'MH', es: 'Islas Marshall', en: 'Marshall Islands' },
  { iso: 'PN', es: 'Islas Pitcairn', en: 'Pitcairn Islands' },
  { iso: 'SB', es: 'Islas Salomón', en: 'Solomon Islands' },
  { iso: 'TC', es: 'Islas Turcas y Caicos', en: 'Turks & Caicos Islands' },
  { iso: 'VG', es: 'Islas Vírgenes Británicas', en: 'British Virgin Islands' },
  { iso: 'VI', es: 'Islas Vírgenes de EE. UU.', en: 'U.S. Virgin Islands' },
  { iso: 'IL', es: 'Israel', en: 'Israel' },
  { iso: 'IT', es: 'Italia', en: 'Italy' },
  { iso: 'JM', es: 'Jamaica', en: 'Jamaica' },
  { iso: 'JP', es: 'Japón', en: 'Japan' },
  { iso: 'JE', es: 'Jersey', en: 'Jersey' },
  { iso: 'JO', es: 'Jordania', en: 'Jordan' },
  { iso: 'KZ', es: 'Kazajistán', en: 'Kazakhstan' },
  { iso: 'KE', es: 'Kenia', en: 'Kenya' },
  { iso: 'KG', es: 'Kirguistán', en: 'Kyrgyzstan' },
  { iso: 'KI', es: 'Kiribati', en: 'Kiribati' },
  { iso: 'XK', es: 'Kosovo', en: 'Kosovo' },
  { iso: 'KW', es: 'Kuwait', en: 'Kuwait' },
  { iso: 'LA', es: 'Laos', en: 'Laos' },
  { iso: 'LS', es: 'Lesoto', en: 'Lesotho' },
  { iso: 'LV', es: 'Letonia', en: 'Latvia' },
  { iso: 'LB', es: 'Líbano', en: 'Lebanon' },
  { iso: 'LR', es: 'Liberia', en: 'Liberia' },
  { iso: 'LY', es: 'Libia', en: 'Libya' },
  { iso: 'LI', es: 'Liechtenstein', en: 'Liechtenstein' },
  { iso: 'LT', es: 'Lituania', en: 'Lithuania' },
  { iso: 'LU', es: 'Luxemburgo', en: 'Luxembourg' },
  { iso: 'MO', es: 'Macao', en: 'Macao' },
  { iso: 'MK', es: 'Macedonia del Norte', en: 'North Macedonia' },
  { iso: 'MG', es: 'Madagascar', en: 'Madagascar' },
  { iso: 'MY', es: 'Malasia', en: 'Malaysia' },
  { iso: 'MW', es: 'Malaui', en: 'Malawi' },
  { iso: 'MV', es: 'Maldivas', en: 'Maldives' },
  { iso: 'ML', es: 'Mali', en: 'Mali' },
  { iso: 'MT', es: 'Malta', en: 'Malta' },
  { iso: 'MA', es: 'Marruecos', en: 'Morocco' },
  { iso: 'MQ', es: 'Martinica', en: 'Martinique' },
  { iso: 'MU', es: 'Mauricio', en: 'Mauritius' },
  { iso: 'MR', es: 'Mauritania', en: 'Mauritania' },
  { iso: 'YT', es: 'Mayotte', en: 'Mayotte' },
  { iso: 'MX', es: 'México', en: 'Mexico' },
  { iso: 'FM', es: 'Micronesia', en: 'Micronesia' },
  { iso: 'MD', es: 'Moldavia', en: 'Moldova' },
  { iso: 'MC', es: 'Mónaco', en: 'Monaco' },
  { iso: 'MN', es: 'Mongolia', en: 'Mongolia' },
  { iso: 'ME', es: 'Montenegro', en: 'Montenegro' },
  { iso: 'MS', es: 'Montserrat', en: 'Montserrat' },
  { iso: 'MZ', es: 'Mozambique', en: 'Mozambique' },
  { iso: 'MM', es: 'Myanmar (Birmania)', en: 'Myanmar (Burma)' },
  { iso: 'NA', es: 'Namibia', en: 'Namibia' },
  { iso: 'NR', es: 'Nauru', en: 'Nauru' },
  { iso: 'NP', es: 'Nepal', en: 'Nepal' },
  { iso: 'NI', es: 'Nicaragua', en: 'Nicaragua' },
  { iso: 'NE', es: 'Níger', en: 'Niger' },
  { iso: 'NG', es: 'Nigeria', en: 'Nigeria' },
  { iso: 'NU', es: 'Niue', en: 'Niue' },
  { iso: 'NO', es: 'Noruega', en: 'Norway' },
  { iso: 'NC', es: 'Nueva Caledonia', en: 'New Caledonia' },
  { iso: 'NZ', es: 'Nueva Zelanda', en: 'New Zealand' },
  { iso: 'OM', es: 'Omán', en: 'Oman' },
  { iso: 'NL', es: 'Países Bajos', en: 'Netherlands' },
  { iso: 'PK', es: 'Pakistán', en: 'Pakistan' },
  { iso: 'PW', es: 'Palaos', en: 'Palau' },
  { iso: 'PA', es: 'Panamá', en: 'Panama' },
  { iso: 'PG', es: 'Papúa Nueva Guinea', en: 'Papua New Guinea' },
  { iso: 'PY', es: 'Paraguay', en: 'Paraguay' },
  { iso: 'PE', es: 'Perú', en: 'Peru' },
  { iso: 'PF', es: 'Polinesia Francesa', en: 'French Polynesia' },
  { iso: 'PL', es: 'Polonia', en: 'Poland' },
  { iso: 'PT', es: 'Portugal', en: 'Portugal' },
  { iso: 'PR', es: 'Puerto Rico', en: 'Puerto Rico' },
  { iso: 'GB', es: 'Reino Unido', en: 'United Kingdom' },
  { iso: 'CF', es: 'República Centroafricana', en: 'Central African Republic' },
  { iso: 'CD', es: 'República Democrática del Congo', en: 'Congo (Kinshasa)' },
  { iso: 'DO', es: 'República Dominicana', en: 'Dominican Republic' },
  { iso: 'RE', es: 'Reunión', en: 'Réunion' },
  { iso: 'RW', es: 'Ruanda', en: 'Rwanda' },
  { iso: 'RO', es: 'Rumanía', en: 'Romania' },
  { iso: 'RU', es: 'Rusia', en: 'Russia' },
  { iso: 'EH', es: 'Sáhara Occidental', en: 'Western Sahara' },
  { iso: 'WS', es: 'Samoa', en: 'Samoa' },
  { iso: 'AS', es: 'Samoa Americana', en: 'American Samoa' },
  { iso: 'BL', es: 'San Bartolomé', en: 'St. Barthélemy' },
  { iso: 'KN', es: 'San Cristóbal y Nieves', en: 'St. Kitts & Nevis' },
  { iso: 'SM', es: 'San Marino', en: 'San Marino' },
  { iso: 'MF', es: 'San Martín', en: 'St. Martin' },
  { iso: 'PM', es: 'San Pedro y Miquelón', en: 'St. Pierre & Miquelon' },
  { iso: 'VC', es: 'San Vicente y las Granadinas', en: 'St. Vincent & Grenadines' },
  { iso: 'SH', es: 'Santa Elena', en: 'St. Helena' },
  { iso: 'LC', es: 'Santa Lucía', en: 'St. Lucia' },
  { iso: 'ST', es: 'Santo Tomé y Príncipe', en: 'São Tomé & Príncipe' },
  { iso: 'SN', es: 'Senegal', en: 'Senegal' },
  { iso: 'RS', es: 'Serbia', en: 'Serbia' },
  { iso: 'SC', es: 'Seychelles', en: 'Seychelles' },
  { iso: 'SL', es: 'Sierra Leona', en: 'Sierra Leone' },
  { iso: 'SG', es: 'Singapur', en: 'Singapore' },
  { iso: 'SX', es: 'Sint Maarten', en: 'Sint Maarten' },
  { iso: 'SY', es: 'Siria', en: 'Syria' },
  { iso: 'SO', es: 'Somalia', en: 'Somalia' },
  { iso: 'LK', es: 'Sri Lanka', en: 'Sri Lanka' },
  { iso: 'ZA', es: 'Sudáfrica', en: 'South Africa' },
  { iso: 'SD', es: 'Sudán', en: 'Sudan' },
  { iso: 'SS', es: 'Sudán del Sur', en: 'South Sudan' },
  { iso: 'SE', es: 'Suecia', en: 'Sweden' },
  { iso: 'CH', es: 'Suiza', en: 'Switzerland' },
  { iso: 'SR', es: 'Surinam', en: 'Suriname' },
  { iso: 'SJ', es: 'Svalbard y Jan Mayen', en: 'Svalbard & Jan Mayen' },
  { iso: 'TH', es: 'Tailandia', en: 'Thailand' },
  { iso: 'TW', es: 'Taiwán', en: 'Taiwan' },
  { iso: 'TZ', es: 'Tanzania', en: 'Tanzania' },
  { iso: 'TJ', es: 'Tayikistán', en: 'Tajikistan' },
  { iso: 'PS', es: 'Territorios Palestinos', en: 'Palestinian Territories' },
  { iso: 'TL', es: 'Timor-Leste', en: 'Timor-Leste' },
  { iso: 'TG', es: 'Togo', en: 'Togo' },
  { iso: 'TK', es: 'Tokelau', en: 'Tokelau' },
  { iso: 'TO', es: 'Tonga', en: 'Tonga' },
  { iso: 'TT', es: 'Trinidad y Tobago', en: 'Trinidad & Tobago' },
  { iso: 'TN', es: 'Túnez', en: 'Tunisia' },
  { iso: 'TM', es: 'Turkmenistán', en: 'Turkmenistan' },
  { iso: 'TR', es: 'Turquía', en: 'Türkiye' },
  { iso: 'TV', es: 'Tuvalu', en: 'Tuvalu' },
  { iso: 'UA', es: 'Ucrania', en: 'Ukraine' },
  { iso: 'UG', es: 'Uganda', en: 'Uganda' },
  { iso: 'UY', es: 'Uruguay', en: 'Uruguay' },
  { iso: 'UZ', es: 'Uzbekistán', en: 'Uzbekistan' },
  { iso: 'VU', es: 'Vanuatu', en: 'Vanuatu' },
  { iso: 'VE', es: 'Venezuela', en: 'Venezuela' },
  { iso: 'VN', es: 'Vietnam', en: 'Vietnam' },
  { iso: 'WF', es: 'Wallis y Futuna', en: 'Wallis & Futuna' },
  { iso: 'YE', es: 'Yemen', en: 'Yemen' },
  { iso: 'DJ', es: 'Yibuti', en: 'Djibouti' },
  { iso: 'ZM', es: 'Zambia', en: 'Zambia' },
  { iso: 'ZW', es: 'Zimbabue', en: 'Zimbabwe' },
];

const POR_ISO = new Map(PAISES.map((p) => [p.iso, p]));

export function pais(iso: string): Pais | null {
  return POR_ISO.get(iso) ?? null;
}

/** Los 27 de la Unión Europea: comparten el arancel común. */
export const UNION_EUROPEA = ['AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE'];
